### PR TITLE
Added few things and made changes to enhance the look

### PR DESCRIPTION
**Pull request by Yashism**
I have added a title to the website and also added a cat's icon to the website. Added background color to the website. Also, I added a font to the heading and the contents to the website.

### CODE REVIEW

**Comment by sattwik21** [comment]
Please just attach a image of the enhanced website i will approve it asap

**Comment by Yashism** [comment]
> Please just attach a image of the enhanced website i will approve it asap

image
Added image, color, and title to the website and you can see the font changed

**Comment by Yashism** [comment]
Here's it is!!! Hope you liked it : )
Portfolio (1)

**Comment by sattwik21** [comment]
Its really great

**Comment by sattwik21** [comment]
> ``

**Pull request merged**
